package it.polimi.sw2019.model.events;

/**
 * This is the interface from which the messages generated by the weapons effect controllers inherit
 * @author Mattia Iamundo
 */
public interface WeaponEvent {

    /**
     * This method return the attacker nickname, so the client could understand if the message it's direct to him or not
     * @return the attacker's nickname
     */
     String getAttacker();
}
