package it.polimi.sw2019.events.weaponeffect_controller_events;

import it.polimi.sw2019.events.NotifyReturn;

/**
 * This is the interface from which the messages generated by the weapons effect controllers inherit
 * @author Mattia Iamundo
 */
public interface WeaponEvent extends NotifyReturn {

}
